# Generated by Django 5.2.7 on 2025-10-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('request', '0002_alter_request_customer_alter_request_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airesponse',
            old_name='audio_file',
            new_name='answer_audio',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_responses', to='request.supervisor'),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='request.request'),
        ),
    ]
