# Generated by Django 5.2.7 on 2025-10-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_audio_file_airesponse_answer_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
