# Generated by Django 5.2.7 on 2025-10-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_customer_alter_request_supervisor'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_responses', to='request.request'),
        ),
        migrations.AlterField(
            model_name='supervisorresponse',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_responses', to='request.supervisor'),
        ),
    ]
